import type { Metadata } from 'next';
import {
  // Geist, Geist_Mono
  Outfit,
} from 'next/font/google';
import './globals.css';
import SideNavBar from '@/components/layout/SideNavBar';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const fontOutfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${fontOutfit.className} relative h-dvh overflow-scroll border border-blue-400`}
      >
        <div className='grid min-h-screen grid-cols-[300px_1fr] grid-rows-[65px_auto]'>
          {/* Header */}
          <header className='z-1 sticky left-0 top-0 col-span-2 flex h-[65px] items-center bg-gray-800 px-4 text-white'>
            <h1>Header</h1>
          </header>

          {/* Aside */}
          <aside className='z-1 sticky left-0 top-[65px] h-[calc(100vh-65px)] bg-[#444450] p-4 text-white'>
            <SideNavBar />
          </aside>

          {/* Main */}
          <main className='bg-gray-100 p-4'>{children}</main>
        </div>
      </body>
    </html>
  );
}
